In [1]:
import numpy as np

In [13]:
#1、打印numpy的版本和配置说明
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/alien/anaconda3/envs/tensorflow/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/alien/anaconda3/envs/tensorflow/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/alien/anaconda3/envs/tensorflow/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/alien/anaconda3/envs/tensorflow/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/alien/anaconda3/envs/tensorflow/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/alien/anaconda3/envs/tensorflow/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/alien/anaconda3/envs/tensorflow/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/alien/anaco

In [15]:
#2、创建一个长度为10的空向量
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
#3、找到一个数组的内存大小
Z=np.zeros((10,10))
print("{} bytes".format(Z.size*Z.itemsize))

800 bytes


In [19]:
#4、得到numpy中add函数的说明文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [21]:
#5、创建一个长度为10但仅有第5个值为1的空向量
z=np.zeros(10)
z[4]=1
print("z:{}".format(z))

z:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [23]:
#6、创建一个值域从10-49的向量
z=np.arange(10,50)
print("{}".format(z))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
#7、反转一个向量
z=np.arange(50)
z=z[::-1]
print("反转z:{}".format(z))

反转z:[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [27]:
#8、创建一个3*3并且值从0-8的矩阵
z=np.arange(9).reshape(3,3)
print("{}".format(z))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
#9、找到数组[1，2，0，0，4，0]中非0元素的位置索引
nz=np.nonzero([1,2,0,0,4,0])
print("{}".format(nz[0]))

[0 1 4]


In [31]:
#10、创建一个3*3的单位矩阵
z=np.eye(3)
print("{}".format(z))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#11、创建一个3*3*3的随机数组
z=np.random.random((3,3,3))
print("{}".format(z))

[[[0.87702991 0.99573791 0.92156747]
  [0.52610924 0.24256811 0.66571549]
  [0.04533796 0.62065039 0.31241093]]

 [[0.69767191 0.51692843 0.58563121]
  [0.11508542 0.56572248 0.11827552]
  [0.54456039 0.41885884 0.73084297]]

 [[0.60944161 0.20896095 0.87842208]
  [0.29530059 0.2510706  0.6075374 ]
  [0.14936496 0.39567899 0.45004554]]]


In [35]:
#12、创建一个10*10的随机数组并找到它的最大最小值
z=np.random.random((10,10))
zMax,zMin=z.max(),z.min()
print(" Max:{} \n Min:{} ".format(zMax,zMin))

Max:0.9831156744631805 
 Min:0.014520374828306926 


In [37]:
#13、创建一个长度为30的向量并求它的平均值
z=np.arange(30)
m=z.mean()
print("{}".format(m))

14.5


In [39]:
#14、创建一个二维数组，其边界值为1，其余为0
z=np.ones((10,10))
z[1:-1,1:-1]=0
print("{}".format(z))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [41]:
#15、对一个数据填充边界0
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print("{}".format(z))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [43]:
#16、以下表达式对运算结果是什么
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


In [45]:
#17、创建一个5*5的矩阵，并设置值1，2，3，4落在其对角线下方位置
z=np.diag(np.arange(4)+1,k=-1)
print("{}".format(z))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [47]:
#18、创建一个8*8矩阵，并设置成棋盘样式
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print("{}".format(z))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [49]:
#19、考虑一个（6，7，8）形状的数组，其第100个元素的索引（x,y,z)是什么
print("{}".format(np.unravel_index(100,(6,7,8))))

(1, 5, 4)


In [50]:
#20、用title函数创建一个8*8的棋盘样式矩阵
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print("{}".format(z))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [51]:
#22、对一个5*5的随机矩阵做归一化
z=np.random.random((5*5))
zMax,zMin=z.max(),z.min()
z=(z-zMin)/(zMax-zMin)
print("{}".format(z))

[0.90645537 0.82998102 0.19300006 0.58124195 1.         0.7691622
 0.07960398 0.60495831 0.14636602 0.27141091 0.8561181  0.73139626
 0.86457609 0.01872523 0.86846689 0.79067696 0.17056288 0.43042853
 0.79744272 0.19514374 0.23532583 0.         0.60585765 0.50989599
 0.947038  ]


In [52]:
#23、创建一个将颜色描述为（RGBA）四个无符号字节的自定义dtype
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [53]:
#24、实现一个5*3的矩阵和3*2的矩阵相乘
z1=np.arange(15).reshape((5,3))
z2=np.arange(6).reshape((3,2))
z=np.dot(z1,z2)
print("{}".format(z))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [54]:
#25、对一个一位数组力值在3—8之间对值取反
z=np.arange(11)
z[(z>3)&(z<=8)]*=-1
print("{}".format(z))

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [55]:
#26、下面脚本的运行结果是什么
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [56]:
#27、考虑整数向量z，下面的表达式正确的是？
z=np.arange(5)
z**z     #legal
2<< z >>2 #legal 二进制左/右移2位
# z<-z    #legal
# 1j*z    #legal
# z/1/1   #legal
# z<z>z   #false


array([0, 1, 2, 4, 8])

In [62]:
#28、下列表达式的结果分别是什么
print(np.array(0)/np.array(0)) 
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


In [66]:
#29、如何从零位对浮点数组做舍入
z=np.random.uniform(-10,10,10)
# print("{}".format(z))
print(np.copysign(np.ceil(np.abs(z)),z))
# print(np.ceil(z))

[ 9. -4.  1.  2. -1.  3. -8. -1. -4. -4.]


In [68]:
#30、如何找到两个数组中对共同元素
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,10)
print("z1:{} \n z2:{}".format(z1,z2))
print("共同元素：{}".format(np.intersect1d(z1,z2)))

z1:[0 0 1 3 7 0 4 6 5 4] 
 z2:[5 0 1 5 9 9 8 5 2 6]
共同元素：[0 1 5 6]


In [72]:
#32、下面表达式正确吗
print(np.sqrt(-1)==np.emath.sqrt(-1))
print("{}".format(np.sqrt(-1)))
print("{}".format(np.emath.sqrt(-1)))


False
nan
1j


In [90]:
#33、如何得到昨天、今天、明天的日期
yestoday=np.datetime64("today","D")-np.timedelta64(1,'D')
today=np.datetime64("today","D")
tomorrow=np.datetime64("today","D")+np.timedelta64(1,"D")
print("昨天：{} \n 今天：{} \n 明天：{}".format(yestoday,today,tomorrow))

昨天：2020-05-04 
 今天：2020-05-05 
 明天：2020-05-06


In [95]:
#34、如何得到所有与2016年7月对应的日期
z=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print("{}".format(z))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [6]:
#35、如何直接在位计算（A+B）*(-A/2)(不建立副本)？
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [8]:
#36、用五种不同的方法去提取一个随机数组的整数部分
z=np.random.uniform(0,10,10)
print(z)
print("{}".format(np.floor(z)))
print("{}".format(np.ceil(z)-1))
print("{}".format(z.astype(int)))
print("{}".format(np.trunc(z)))
print("{}".format(z-z%1))


[9.90283596 8.18648103 5.12413074 5.72597877 4.02834261 1.93934477
 3.3617947  9.34260099 0.88593123 2.58482687]
[9. 8. 5. 5. 4. 1. 3. 9. 0. 2.]
[9. 8. 5. 5. 4. 1. 3. 9. 0. 2.]
[9 8 5 5 4 1 3 9 0 2]
[9. 8. 5. 5. 4. 1. 3. 9. 0. 2.]
[9. 8. 5. 5. 4. 1. 3. 9. 0. 2.]


In [12]:
#37、创建一个5*5的矩阵，其中每行的数值范围从0到4
z=np.zeros((5,5))
z+=np.arange(5)
print("{}".format(z))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [14]:
#38、通过考虑一个可生成10个整数的函数，来构建一个数组(知识点：yield,np.fromiter())
pass

In [20]:
#39、创建一个长度为10的随机向量，其值域范围从0到1，但不包括0和1
z=np.linspace(1,10,11,endpoint=False)[1:]
print("{}".format(z))

[1.81818182 2.63636364 3.45454545 4.27272727 5.09090909 5.90909091
 6.72727273 7.54545455 8.36363636 9.18181818]


In [22]:
#40、创建一个长度为10的随机向量，并将其排序
z=np.random.uniform(0,10,10)
z.sort()
print("{}".format(z))

[0.30684704 0.96309331 1.3811795  3.37556001 3.73773065 4.59482655
 7.79783001 7.86186134 7.92287837 9.32223961]


In [37]:
#41、对于一个数组，如何用比np.sum更快的方式对其求和
z=np.arange(9).reshape(3,3)
print("{}".format(z))
print("{}".format(np.add.reduce(z,axis=0)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]


In [38]:
#42、对于两个随机数组A和B，检查它们是否相等
A=np.random.randint(0,10,10)
B=np.random.randint(0,10,10)
#方法一
equal=np.allclose(A,B)
print("{}".format(equal))
equal=np.array_equal(A,B)
print("{}".format(equal))

False
False


In [41]:
#43、创建一个只读数组
z=np.arange(10)
z.flags.writeable=False
# z[0]=1

In [42]:
#44、将笛卡尔坐标下的一个10*2的矩阵转换为极坐标形式
pass

In [44]:
#45、创建一个长度为10的向量，并将向量中的最大值替换为1
z=np.random.uniform(0,10,10)
print("{}".format(z))
z[z.argmax()]=1
print("{}".format(z))

[4.69838751 1.70707764 3.90154214 1.51811934 4.71053803 8.33070324
 1.68670985 5.05163176 3.89557144 0.06140486]
[4.69838751 1.70707764 3.90154214 1.51811934 4.71053803 1.
 1.68670985 5.05163176 3.89557144 0.06140486]


In [ ]:
#46、